import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import fastifyStatic from '@fastify/static';
import rawBody from 'fastify-raw-body';
import { config, ensureProductionSecrets } from './config.js';
import { ensureCsrf } from './auth.js';
import { query } from './db.js';
import authRoutes from './routes/auth.js';
import accountRoutes from './routes/account.js';
import productRoutes from './routes/products.js';
import cartRoutes from './routes/cart.js';
import orderRoutes from './routes/orders.js';
import paymentRoutes from './routes/payments.js';
import adminRoutes from './routes/admin.js';
import newsletterRoutes from './routes/newsletter.js';

ensureProductionSecrets();
const app=Fastify({logger:true,bodyLimit:1_000_000,trustProxy:config.isProd});
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const publicRoot=path.resolve(process.env.PUBLIC_ROOT || path.join(__dirname,'../../'));
await app.register(cookie);
await app.register(helmet,{contentSecurityPolicy:false,crossOriginEmbedderPolicy:false});
await app.register(rateLimit,{global:true,max:120,timeWindow:'1 minute',errorResponseBuilder:()=>({error:'Too many requests. Please try again shortly.'})});
await app.register(rawBody,{field:'rawBody',global:false,encoding:false,runFirst:true});
await app.register(fastifyStatic,{root:publicRoot,prefix:'/'});
app.addHook('onRequest',async(request,reply)=>{if(request.url.startsWith('/api/')&&!request.url.startsWith('/api/payments/webhook'))ensureCsrf(request,reply);});
app.get('/api/health',async()=>{ const result=await query('SELECT 1 AS ok'); return {ok:result.rows[0]?.ok===1,service:'mistic-aura-api',time:new Date().toISOString(),environment:config.nodeEnv}; });
await app.register(authRoutes);await app.register(accountRoutes);await app.register(productRoutes);await app.register(cartRoutes);await app.register(orderRoutes);await app.register(paymentRoutes);await app.register(adminRoutes);
await app.register(newsletterRoutes);
app.setErrorHandler((error,request,reply)=>{request.log.error(error);if(error.code==='ER_DUP_ENTRY' || error.errno===1062)return reply.code(409).send({error:'That value is already in use.'});if(error.name==='ZodError')return reply.code(400).send({error:'Please check the submitted information.',details:error.issues.map(i=>({field:i.path.join('.'),message:i.message}))});return reply.code(error.statusCode||500).send({error:config.isProd&&!error.statusCode?'Something went wrong.':error.message});});
app.get('/*',async(request,reply)=>{if(request.url.startsWith('/api/'))return reply.code(404).send({error:'API route not found'});return reply.sendFile('index.html');});
await app.listen({port:config.port,host:'0.0.0.0'});
