import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import { query } from '../db.js';
import { requireUser, verifyCsrf } from '../auth.js';

const addressSchema=z.object({label:z.string().trim().min(1).max(50).default('Home'),firstName:z.string().trim().min(1).max(80),lastName:z.string().trim().min(1).max(80),addressLine1:z.string().trim().min(1).max(200),addressLine2:z.string().trim().max(200).optional().nullable(),suburb:z.string().trim().min(1).max(100),state:z.string().trim().min(1).max(50),postcode:z.string().trim().regex(/^\d{4}$/),country:z.literal('AU').default('AU'),isDefaultShipping:z.boolean().default(false),isDefaultBilling:z.boolean().default(false)});

export default async function accountRoutes(app){
  app.get('/api/account',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;const [u,a,o]=await Promise.all([query('SELECT id,email,first_name,last_name,phone,email_verified_at,marketing_opt_in,created_at FROM users WHERE id=$1',[s.user_id]),query('SELECT * FROM addresses WHERE user_id=$1 ORDER BY is_default_shipping DESC,created_at DESC',[s.user_id]),query('SELECT id,order_number,status,payment_status,total,currency,created_at FROM orders WHERE user_id=$1 ORDER BY created_at DESC',[s.user_id])]);return {user:u.rows[0],addresses:a.rows,orders:o.rows};});
  app.patch('/api/account',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;verifyCsrf(request);const b=z.object({firstName:z.string().trim().min(1).max(80),lastName:z.string().trim().min(1).max(80),phone:z.string().trim().max(30).optional().nullable()}).parse(request.body);await query('UPDATE users SET first_name=$1,last_name=$2,phone=$3,updated_at=NOW(3) WHERE id=$4',[b.firstName,b.lastName,b.phone||null,s.user_id]);const r=await query('SELECT id,email,first_name,last_name,phone FROM users WHERE id=$1',[s.user_id]);return {user:r.rows[0]};});
  app.get('/api/account/addresses',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;return {addresses:(await query('SELECT * FROM addresses WHERE user_id=$1 ORDER BY created_at DESC',[s.user_id])).rows};});
  app.post('/api/account/addresses',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;verifyCsrf(request);const b=addressSchema.parse(request.body);const id=randomUUID();await query(`INSERT INTO addresses(id,user_id,label,first_name,last_name,address_line_1,address_line_2,suburb,state,postcode,country,is_default_shipping,is_default_billing) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[id,s.user_id,b.label,b.firstName,b.lastName,b.addressLine1,b.addressLine2||null,b.suburb,b.state,b.postcode,b.country,b.isDefaultShipping?1:0,b.isDefaultBilling?1:0]);if(b.isDefaultShipping)await query('UPDATE addresses SET is_default_shipping=0 WHERE user_id=$1 AND id<>$2',[s.user_id,id]);if(b.isDefaultBilling)await query('UPDATE addresses SET is_default_billing=0 WHERE user_id=$1 AND id<>$2',[s.user_id,id]);return reply.code(201).send({address:(await query('SELECT * FROM addresses WHERE id=$1',[id])).rows[0]});});
  app.patch('/api/account/addresses/:id',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;verifyCsrf(request);const b=addressSchema.partial().parse(request.body);const r0=await query('SELECT * FROM addresses WHERE id=$1 AND user_id=$2',[request.params.id,s.user_id]);if(!r0.rows[0])return reply.code(404).send({error:'Address not found'});const o=r0.rows[0],m={label:b.label??o.label,firstName:b.firstName??o.first_name,lastName:b.lastName??o.last_name,addressLine1:b.addressLine1??o.address_line_1,addressLine2:b.addressLine2??o.address_line_2,suburb:b.suburb??o.suburb,state:b.state??o.state,postcode:b.postcode??o.postcode,country:b.country??o.country,isDefaultShipping:b.isDefaultShipping??!!o.is_default_shipping,isDefaultBilling:b.isDefaultBilling??!!o.is_default_billing};await query(`UPDATE addresses SET label=$1,first_name=$2,last_name=$3,address_line_1=$4,address_line_2=$5,suburb=$6,state=$7,postcode=$8,country=$9,is_default_shipping=$10,is_default_billing=$11,updated_at=NOW(3) WHERE id=$12`,[m.label,m.firstName,m.lastName,m.addressLine1,m.addressLine2||null,m.suburb,m.state,m.postcode,m.country,m.isDefaultShipping?1:0,m.isDefaultBilling?1:0,request.params.id]);if(m.isDefaultShipping)await query('UPDATE addresses SET is_default_shipping=0 WHERE user_id=$1 AND id<>$2',[s.user_id,request.params.id]);if(m.isDefaultBilling)await query('UPDATE addresses SET is_default_billing=0 WHERE user_id=$1 AND id<>$2',[s.user_id,request.params.id]);return {address:(await query('SELECT * FROM addresses WHERE id=$1',[request.params.id])).rows[0]};});
  app.delete('/api/account/addresses/:id',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;verifyCsrf(request);const r=await query('SELECT id FROM addresses WHERE id=$1 AND user_id=$2',[request.params.id,s.user_id]);if(!r.rows[0])return reply.code(404).send({error:'Address not found'});await query('DELETE FROM addresses WHERE id=$1 AND user_id=$2',[request.params.id,s.user_id]);return {ok:true};});
}
