import { z } from 'zod';
import speakeasy from 'speakeasy';
import { randomUUID } from 'node:crypto';
import { query } from '../db.js';
import { hashPassword, verifyPassword, createSession, requireAdmin, revokeSession, verifyCsrf } from '../auth.js';
import { encrypt, decrypt } from '../crypto.js';

export default async function adminRoutes(app){
 app.post('/api/admin/auth/login',async(request,reply)=>{verifyCsrf(request);const b=z.object({email:z.string().trim().toLowerCase().email(),password:z.string().min(1),mfaCode:z.string().regex(/^\d{6}$/).optional()}).parse(request.body);const r=await query('SELECT * FROM admin_users WHERE email=?',[b.email]);const a=r.rows[0],valid=a?await verifyPassword(a.password_hash,b.password).catch(()=>false):false;if(!valid||a.status!=='active')return reply.code(401).send({error:'Email or password is incorrect.'});if(!a.mfa_enabled)return reply.code(403).send({error:'Admin MFA is not enabled for this account.'});if(!b.mfaCode)return reply.code(401).send({error:'MFA code required.',code:'MFA_REQUIRED'});const secret=decrypt(a.mfa_secret_encrypted);if(!speakeasy.totp.verify({secret,encoding:'base32',token:b.mfaCode,window:1}))return reply.code(401).send({error:'Invalid MFA code.',code:'MFA_INVALID'});await query('UPDATE admin_users SET last_login_at=NOW(3),updated_at=NOW(3) WHERE id=$1',[a.id]);await createSession({adminUserId:a.id,request,reply});await query(`INSERT INTO audit_logs(id,admin_user_id,action,entity_type,entity_id,ip_address,user_agent,metadata) VALUES($1,$2,'ADMIN_LOGIN','admin_user',$2,$3,$4,JSON_OBJECT())`,[randomUUID(),a.id,request.ip,request.headers['user-agent']||null]);return {admin:{id:a.id,email:a.email,firstName:a.first_name,lastName:a.last_name,role:a.role}};});
 app.post('/api/admin/auth/logout',async(request,reply)=>{verifyCsrf(request);await revokeSession(request,reply);return {ok:true};});
 app.get('/api/admin/me',async(request,reply)=>{const s=await requireAdmin(request,reply);if(!s)return;return {admin:{id:s.admin_user_id,email:s.admin_email,firstName:s.admin_first_name,lastName:s.admin_last_name,role:s.admin_role}};});
 app.get('/api/admin/orders',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin','support','fulfilment']);if(!s)return;return {orders:(await query(`SELECT o.id,o.order_number,o.status,o.payment_status,o.total,o.currency,o.created_at,u.email,u.first_name,u.last_name FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 200`)).rows};});
 app.get('/api/admin/customers',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin','support']);if(!s)return;return {customers:(await query(`SELECT id,email,first_name,last_name,phone,email_verified_at,status,marketing_opt_in,created_at,last_login_at FROM users ORDER BY created_at DESC LIMIT 500`)).rows};});
 app.get('/api/admin/products',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin']);if(!s)return;const r=await query(`SELECT p.id,p.slug,p.name,p.brand,p.description,p.collection,p.family,p.image_url,p.is_active,p.is_featured,p.is_best_seller,p.created_at,p.updated_at,COALESCE(JSON_ARRAYAGG(CASE WHEN v.id IS NULL THEN NULL ELSE JSON_OBJECT('id',v.id,'name',v.name,'sku',v.sku,'price',v.price,'currency',v.currency,'quantityDescription',v.quantity_description) END),JSON_ARRAY()) variants FROM products p LEFT JOIN product_variants v ON v.product_id=p.id GROUP BY p.id ORDER BY p.collection,p.name`);return {products:r.rows.map(x=>({...x,variants:(Array.isArray(x.variants)?x.variants:JSON.parse(x.variants||'[]')).filter(Boolean)}))};});
 app.patch('/api/admin/orders/:id',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin','fulfilment']);if(!s)return;verifyCsrf(request);const b=z.object({status:z.enum(['pending_payment','paid','processing','shipped','delivered','cancelled','refunded'])}).parse(request.body);const old=await query('SELECT status FROM orders WHERE id=$1',[request.params.id]);if(!old.rows[0])return reply.code(404).send({error:'Order not found'});await query('UPDATE orders SET status=$1,updated_at=NOW(3) WHERE id=$2',[b.status,request.params.id]);await query(`INSERT INTO audit_logs(id,admin_user_id,action,entity_type,entity_id,ip_address,user_agent,metadata) VALUES($1,$2,'ORDER_STATUS_CHANGED','order',$3,$4,$5,$6)`,[randomUUID(),s.admin_user_id,request.params.id,request.ip,request.headers['user-agent']||null,JSON.stringify({from:old.rows[0].status,to:b.status})]);return {order:(await query('SELECT * FROM orders WHERE id=$1',[request.params.id])).rows[0]};});
 app.patch('/api/admin/products/:id/variant/:variantId',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin']);if(!s)return;verifyCsrf(request);const b=z.object({price:z.number().min(0).max(100000),isActive:z.boolean().optional()}).parse(request.body);const old=await query('SELECT price FROM product_variants WHERE id=$1 AND product_id=$2',[request.params.variantId,request.params.id]);if(!old.rows[0])return reply.code(404).send({error:'Variant not found'});await query('UPDATE product_variants SET price=$1,is_active=COALESCE($2,is_active),updated_at=NOW(3) WHERE id=$3',[b.price,b.isActive==null?null:(b.isActive?1:0),request.params.variantId]);await query(`INSERT INTO audit_logs(id,admin_user_id,action,entity_type,entity_id,ip_address,user_agent,metadata) VALUES($1,$2,'PRODUCT_PRICE_CHANGED','product_variant',$3,$4,$5,$6)`,[randomUUID(),s.admin_user_id,request.params.variantId,request.ip,request.headers['user-agent']||null,JSON.stringify({from:Number(old.rows[0].price),to:b.price})]);return {variant:(await query('SELECT * FROM product_variants WHERE id=$1',[request.params.variantId])).rows[0]};});
 app.get('/api/admin/audit-logs',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin']);if(!s)return;return {logs:(await query(`SELECT al.*,a.email admin_email FROM audit_logs al LEFT JOIN admin_users a ON a.id=al.admin_user_id ORDER BY al.created_at DESC LIMIT 500`)).rows};});
 app.post('/api/admin/mfa/setup',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin']);if(!s)return;verifyCsrf(request);const secret=speakeasy.generateSecret({name:`Mistic Aura (${s.admin_email})`,length:20});await query('UPDATE admin_users SET mfa_secret_encrypted=$1,updated_at=NOW(3) WHERE id=$2',[encrypt(secret.base32),s.admin_user_id]);return {secret:secret.base32,otpauthUrl:secret.otpauth_url};});
 app.post('/api/admin/mfa/enable',async(request,reply)=>{const s=await requireAdmin(request,reply,['super_admin','admin']);if(!s)return;verifyCsrf(request);const b=z.object({code:z.string().regex(/^\d{6}$/)}).parse(request.body);const r=await query('SELECT mfa_secret_encrypted FROM admin_users WHERE id=$1',[s.admin_user_id]);if(!r.rows[0]?.mfa_secret_encrypted)return reply.code(400).send({error:'Start MFA setup first.'});if(!speakeasy.totp.verify({secret:decrypt(r.rows[0].mfa_secret_encrypted),encoding:'base32',token:b.code,window:1}))return reply.code(400).send({error:'Invalid MFA code.'});await query('UPDATE admin_users SET mfa_enabled=1,updated_at=NOW(3) WHERE id=$1',[s.admin_user_id]);await query(`INSERT INTO audit_logs(id,admin_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'MFA_ENABLED','admin_user',$2,JSON_OBJECT())`,[randomUUID(),s.admin_user_id]);return {ok:true};});
}
