import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import { query } from '../db.js';
import { getSession, verifyCsrf } from '../auth.js';
import { randomToken, sha256 } from '../crypto.js';
const itemSchema=z.object({variantId:z.string().uuid(),quantity:z.number().int().min(1).max(99)});
async function getCart({userId,guestToken}){if(userId){let r=await query('SELECT * FROM carts WHERE user_id=$1',[userId]);if(!r.rows[0]){const id=randomUUID();await query('INSERT INTO carts(id,user_id) VALUES($1,$2)',[id,userId]);r=await query('SELECT * FROM carts WHERE id=$1',[id]);}return r.rows[0];}if(!guestToken)return null;const r=await query('SELECT * FROM carts WHERE guest_token_hash=$1',[sha256(guestToken)]);return r.rows[0]||null;}
async function payload(id){if(!id)return {items:[],subtotal:0,currency:'AUD'};const r=await query(`SELECT ci.id,ci.quantity,v.id variant_id,v.name variant_name,v.sku,v.price,v.currency,p.id product_id,p.slug,p.name,p.image_url,p.collection,p.family FROM cart_items ci JOIN product_variants v ON v.id=ci.product_variant_id JOIN products p ON p.id=v.product_id WHERE ci.cart_id=$1 ORDER BY ci.created_at`,[id]);const items=r.rows.map(x=>({...x,price:Number(x.price),lineTotal:Number(x.price)*x.quantity}));return {items,subtotal:items.reduce((s,x)=>s+x.lineTotal,0),currency:'AUD'};}
function setGuest(reply,raw){reply.setCookie('mistic_guest',raw,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*30});}
export default async function cartRoutes(app){
 app.get('/api/cart',async request=>{const s=await getSession(request);const c=await getCart({userId:s?.user_id,guestToken:request.cookies.mistic_guest});return payload(c?.id);});
 app.post('/api/cart/items',async(request,reply)=>{verifyCsrf(request);const b=itemSchema.parse(request.body);const s=await getSession(request);let c=await getCart({userId:s?.user_id,guestToken:request.cookies.mistic_guest});if(!c){const raw=randomToken(32);const id=randomUUID();await query('INSERT INTO carts(id,guest_token_hash) VALUES($1,$2)',[id,sha256(raw)]);c=(await query('SELECT * FROM carts WHERE id=$1',[id])).rows[0];setGuest(reply,raw);}const v=await query('SELECT id FROM product_variants WHERE id=$1 AND is_active=1',[b.variantId]);if(!v.rows[0])return reply.code(404).send({error:'Product variant not found'});const existing=await query('SELECT id,quantity FROM cart_items WHERE cart_id=$1 AND product_variant_id=$2',[c.id,b.variantId]);if(existing.rows[0]){await query('UPDATE cart_items SET quantity=LEAST(99,quantity+$1),updated_at=NOW(3) WHERE id=$2',[b.quantity,existing.rows[0].id]);}else{await query('INSERT INTO cart_items(id,cart_id,product_variant_id,quantity) VALUES($1,$2,$3,$4)',[randomUUID(),c.id,b.variantId,b.quantity]);}await query('UPDATE carts SET updated_at=NOW(3) WHERE id=$1',[c.id]);return payload(c.id);});
 app.patch('/api/cart/items/:id',async(request,reply)=>{verifyCsrf(request);const b=z.object({quantity:z.number().int().min(1).max(99)}).parse(request.body);const s=await getSession(request);const c=await getCart({userId:s?.user_id,guestToken:request.cookies.mistic_guest});if(!c)return reply.code(404).send({error:'Cart not found'});const r=await query('UPDATE cart_items SET quantity=$1,updated_at=NOW(3) WHERE id=$2 AND cart_id=$3',[b.quantity,request.params.id,c.id]);if(!r.rowCount)return reply.code(404).send({error:'Cart item not found'});return payload(c.id);});
 app.delete('/api/cart/items/:id',async(request,reply)=>{verifyCsrf(request);const s=await getSession(request);const c=await getCart({userId:s?.user_id,guestToken:request.cookies.mistic_guest});if(!c)return reply.code(404).send({error:'Cart not found'});await query('DELETE FROM cart_items WHERE id=$1 AND cart_id=$2',[request.params.id,c.id]);return payload(c.id);});
}
