import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import { withTransaction, query } from '../db.js';
import { requireUser, verifyCsrf } from '../auth.js';
const address=z.object({firstName:z.string().min(1).max(80),lastName:z.string().min(1).max(80),addressLine1:z.string().min(1).max(200),addressLine2:z.string().max(200).optional().nullable(),suburb:z.string().min(1).max(100),state:z.string().min(1).max(50),postcode:z.string().regex(/^\d{4}$/)});
export default async function orderRoutes(app){
 app.get('/api/orders',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;return {orders:(await query('SELECT id,order_number,status,payment_status,total,currency,created_at FROM orders WHERE user_id=$1 ORDER BY created_at DESC',[s.user_id])).rows};});
 app.get('/api/orders/:id',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;const o=await query('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[request.params.id,s.user_id]);if(!o.rows[0])return reply.code(404).send({error:'Order not found'});const items=await query('SELECT * FROM order_items WHERE order_id=$1 ORDER BY created_at',[request.params.id]);return {order:o.rows[0],items:items.rows};});
 app.post('/api/orders',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;verifyCsrf(request);const b=z.object({shippingAddress:address}).parse(request.body);const order=await withTransaction(async c=>{const cart=await c.query('SELECT id FROM carts WHERE user_id=$1 FOR UPDATE',[s.user_id]);if(!cart.rows[0])throw Object.assign(new Error('Your bag is empty.'),{statusCode:400});const items=await c.query(`SELECT ci.quantity,v.id variant_id,v.sku,v.name variant_name,v.price,v.currency,p.id product_id,p.name product_name FROM cart_items ci JOIN product_variants v ON v.id=ci.product_variant_id JOIN products p ON p.id=v.product_id WHERE ci.cart_id=$1 AND v.is_active=1 FOR UPDATE`,[cart.rows[0].id]);if(!items.rows.length)throw Object.assign(new Error('Your bag is empty.'),{statusCode:400});const subtotal=items.rows.reduce((n,i)=>n+Number(i.price)*i.quantity,0);const shipping=subtotal>75?0:9.95;const total=subtotal+shipping;const number=`MA-${new Date().getFullYear()}-${Date.now().toString(36).toUpperCase()}`;const orderId=randomUUID();await c.query(`INSERT INTO orders(id,user_id,order_number,subtotal,shipping,total,shipping_first_name,shipping_last_name,shipping_address_line_1,shipping_address_line_2,shipping_suburb,shipping_state,shipping_postcode,shipping_country) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[orderId,s.user_id,number,subtotal,shipping,total,b.shippingAddress.firstName,b.shippingAddress.lastName,b.shippingAddress.addressLine1,b.shippingAddress.addressLine2||null,b.shippingAddress.suburb,b.shippingAddress.state,b.shippingAddress.postcode,'AU']);for(const i of items.rows)await c.query(`INSERT INTO order_items(id,order_id,product_id,product_variant_id,product_name_snapshot,variant_name_snapshot,sku_snapshot,unit_price,quantity,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[randomUUID(),orderId,i.product_id,i.variant_id,i.product_name,i.variant_name,i.sku,i.price,i.quantity,Number(i.price)*i.quantity]);await c.query('DELETE FROM cart_items WHERE cart_id=$1',[cart.rows[0].id]);return (await c.query('SELECT * FROM orders WHERE id=$1',[orderId])).rows[0];});return reply.code(201).send({order});});
}
