import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import Stripe from 'stripe';
import { query } from '../db.js';
import { requireUser, verifyCsrf } from '../auth.js';
import { config } from '../config.js';
export default async function paymentRoutes(app){
 const stripe=config.stripeSecretKey?new Stripe(config.stripeSecretKey):null;
 app.post('/api/payments/checkout-session',async(request,reply)=>{const s=await requireUser(request,reply);if(!s)return;verifyCsrf(request);if(!stripe)return reply.code(503).send({error:'Payments are not configured yet. Add STRIPE_SECRET_KEY before enabling checkout.'});const b=z.object({orderId:z.string().uuid()}).parse(request.body);const o=await query('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[b.orderId,s.user_id]);if(!o.rows[0])return reply.code(404).send({error:'Order not found'});if(o.rows[0].payment_status==='paid')return reply.code(409).send({error:'Order is already paid.'});const items=await query('SELECT * FROM order_items WHERE order_id=$1',[b.orderId]);const lineItems=items.rows.map(i=>({price_data:{currency:config.stripeCurrency,product_data:{name:`${i.product_name_snapshot} — ${i.variant_name_snapshot}`},unit_amount:Math.round(Number(i.unit_price)*100)},quantity:i.quantity}));if(Number(o.rows[0].shipping)>0)lineItems.push({price_data:{currency:config.stripeCurrency,product_data:{name:'Australia-wide shipping'},unit_amount:Math.round(Number(o.rows[0].shipping)*100)},quantity:1});const checkout=await stripe.checkout.sessions.create({mode:'payment',line_items:lineItems,customer_email:s.email,metadata:{orderId:o.rows[0].id,orderNumber:o.rows[0].order_number},success_url:`${config.publicAppUrl}/checkout.html?payment=success&order=${o.rows[0].id}`,cancel_url:`${config.publicAppUrl}/checkout.html?payment=cancelled&order=${o.rows[0].id}`});await query(`INSERT INTO payments(id,order_id,provider,provider_session_id,amount,currency,status) VALUES($1,$2,'stripe',$3,$4,'AUD','pending')`,[randomUUID(),o.rows[0].id,checkout.id,o.rows[0].total]);return {url:checkout.url};});
 app.post('/api/payments/webhook',{config:{rawBody:true}},async(request,reply)=>{if(!stripe||!config.stripeWebhookSecret)return reply.code(503).send({error:'Stripe webhook is not configured.'});let event;try{event=stripe.webhooks.constructEvent(request.rawBody,request.headers['stripe-signature'],config.stripeWebhookSecret);}catch(e){return reply.code(400).send({error:`Webhook signature verification failed: ${e.message}`});}const existing=await query('SELECT id FROM webhook_events WHERE provider=$1 AND event_id=$2',['stripe',event.id]);if(existing.rows[0])return {received:true,duplicate:true};const eventId=randomUUID();await query(`INSERT INTO webhook_events(id,provider,event_id,event_type,payload) VALUES($1,'stripe',$2,$3,$4)`,[eventId,event.id,event.type,JSON.stringify(event)]);if(event.type==='checkout.session.completed'){const ss=event.data.object,id=ss.metadata?.orderId;if(id){await query(`UPDATE orders SET payment_status='paid',status='paid',updated_at=NOW(3) WHERE id=$1 AND payment_status<>'paid'`,[id]);await query(`UPDATE payments SET provider_payment_id=$1,status='paid',updated_at=NOW(3) WHERE provider='stripe' AND provider_session_id=$2`,[ss.payment_intent||null,ss.id]);}}await query('UPDATE webhook_events SET processed_at=NOW(3) WHERE id=$1',[eventId]);return {received:true};});
}
